"""Falcon Intelligence framework package."""

from falcon_intel.audit import (
    MatchAuditEvent,
    build_card_viewed_event,
    build_evidence_opened_event,
    build_historical_comp_justification_event,
    build_match_audit_event,
    build_match_rejected_event,
    build_match_selected_event,
)
from falcon_intel.core import AppProfile
from falcon_intel.data_passport import (
    ConfidenceDimensions,
    DataPassport,
    SearchableStatus,
    VerificationStatus,
    build_confidence_dimensions,
    build_data_passport,
)
from falcon_intel.data_passport_lookup import (
    DataPassportLookupResponse,
    load_synthetic_data_passports,
    lookup_data_passport_detail,
)
from falcon_intel.discovery import AssignmentCandidate, discover_assignments
from falcon_intel.evidence_link import (
    EVIDENCE_ACCESS_LEVEL_CODES,
    EvidenceAccessLevel,
    EvidenceLink,
    EvidenceLinkStatus,
    EvidenceSourceDocumentType,
    build_comparable_support_evidence_link,
    build_evidence_link,
    build_market_support_evidence_link,
    build_source_document_evidence_link,
    build_source_report_evidence_link,
)
from falcon_intel.falcon_api_contract import (
    FalconCardBoundaryResponse,
    build_falcon_intelligence_card_response,
)
from falcon_intel.falcon_passport_contract import (
    FalconPassportDetailBoundaryResponse,
    build_falcon_passport_detail_response,
)
from falcon_intel.historical_comp import (
    HISTORICAL_COMP_REASON_CODES,
    HistoricalCompJustificationRecord,
    HistoricalCompJustificationResult,
    HistoricalCompReasonCode,
    build_historical_comp_justification,
)
from falcon_intel.intelligence_card import (
    FirmIntelligenceCard,
    IntelligenceCardConfidenceProvenanceSummary,
    IntelligenceCardMatchGroupSummary,
    IntelligenceCardOrderSummary,
    IntelligenceCardRecommendedAction,
    IntelligenceCardTopMatch,
    IntelligenceCardWarning,
    build_firm_intelligence_card,
)
from falcon_intel.intelligence_matcher import (
    FakeOrder,
    FirmIntelligenceMatchResult,
    IntelligenceMatch,
    load_synthetic_verified_intelligence,
    match_firm_intelligence,
)
from falcon_intel.manifest import (
    SavedManifestInfo,
    ScanManifest,
    create_scan_manifest,
    latest_manifest_path,
    list_saved_manifests,
    save_scan_manifest,
)
from falcon_intel.match_policy import (
    AuditEventCode,
    MatchCategoryCode,
    RecommendedActionCode,
    WarningCode,
)
from falcon_intel.passport_detail_drawer import (
    PassportDetailDrawer,
    PassportDrawerEvidenceLinkSummary,
    PassportDrawerFactSummary,
    PassportDrawerIdentity,
    PassportDrawerVerificationSummary,
    PassportDrawerWarning,
    build_passport_detail_drawer,
)
from falcon_intel.profile import (
    AssignmentProfile,
    build_assignment_profile,
    save_assignment_profile,
)
from falcon_intel.scanner import FileMetadata, scan_metadata
from falcon_intel.search import (
    ManifestSearchQuery,
    ManifestSearchResult,
    ManifestSummary,
    is_likely_report_candidate,
    load_manifest,
    search_manifest,
    search_manifest_files,
    summarize_results,
)

__all__ = [
    "AppProfile",
    "AssignmentCandidate",
    "AssignmentProfile",
    "AuditEventCode",
    "ConfidenceDimensions",
    "EVIDENCE_ACCESS_LEVEL_CODES",
    "DataPassport",
    "DataPassportLookupResponse",
    "EvidenceAccessLevel",
    "EvidenceLink",
    "EvidenceLinkStatus",
    "EvidenceSourceDocumentType",
    "FalconCardBoundaryResponse",
    "FalconPassportDetailBoundaryResponse",
    "FileMetadata",
    "FakeOrder",
    "FirmIntelligenceCard",
    "FirmIntelligenceMatchResult",
    "HISTORICAL_COMP_REASON_CODES",
    "HistoricalCompJustificationRecord",
    "HistoricalCompJustificationResult",
    "HistoricalCompReasonCode",
    "IntelligenceCardConfidenceProvenanceSummary",
    "IntelligenceCardMatchGroupSummary",
    "IntelligenceCardOrderSummary",
    "IntelligenceCardRecommendedAction",
    "IntelligenceCardTopMatch",
    "IntelligenceCardWarning",
    "IntelligenceMatch",
    "SavedManifestInfo",
    "ScanManifest",
    "SearchableStatus",
    "ManifestSearchQuery",
    "ManifestSearchResult",
    "ManifestSummary",
    "MatchAuditEvent",
    "MatchCategoryCode",
    "PassportDetailDrawer",
    "PassportDrawerEvidenceLinkSummary",
    "PassportDrawerFactSummary",
    "PassportDrawerIdentity",
    "PassportDrawerVerificationSummary",
    "PassportDrawerWarning",
    "RecommendedActionCode",
    "VerificationStatus",
    "build_assignment_profile",
    "build_card_viewed_event",
    "build_confidence_dimensions",
    "build_comparable_support_evidence_link",
    "build_data_passport",
    "build_evidence_link",
    "build_evidence_opened_event",
    "build_falcon_intelligence_card_response",
    "build_falcon_passport_detail_response",
    "build_firm_intelligence_card",
    "build_historical_comp_justification_event",
    "build_historical_comp_justification",
    "build_match_audit_event",
    "build_match_rejected_event",
    "build_match_selected_event",
    "build_market_support_evidence_link",
    "build_passport_detail_drawer",
    "build_source_document_evidence_link",
    "build_source_report_evidence_link",
    "create_scan_manifest",
    "discover_assignments",
    "is_likely_report_candidate",
    "latest_manifest_path",
    "list_saved_manifests",
    "load_manifest",
    "load_synthetic_verified_intelligence",
    "load_synthetic_data_passports",
    "lookup_data_passport_detail",
    "match_firm_intelligence",
    "save_assignment_profile",
    "save_scan_manifest",
    "search_manifest",
    "search_manifest_files",
    "scan_metadata",
    "summarize_results",
    "WarningCode",
]
